# Generated by Django 4.2 on 2023-04-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_todo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='name',
        ),
        migrations.AddField(
            model_name='author',
            name='student_class',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='student_division',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
    ]
