# Generated by Django 4.2 on 2023-04-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_author_name_author_student_class_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='student_class',
        ),
        migrations.RemoveField(
            model_name='author',
            name='student_division',
        ),
        migrations.AddField(
            model_name='author',
            name='name',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
    ]
